version: "3.8"

services:
  # Frontend service for integration testing
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=http://localhost:3000
        - REACT_APP_WS_URL=ws://localhost:3000/ws
        - REACT_APP_BACKEND_HOST=localhost
        - REACT_APP_BACKEND_PORT=3000
        - BUILD_OPTIMIZATION=true
        - GENERATE_SOURCEMAP=false
    image: qwen-frontend:integration-test
    container_name: qwen-frontend-test
    restart: unless-stopped

    ports:
      - "8080:80" # Use port 8080 for frontend

    environment:
      - NODE_ENV=production
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_WS_URL=ws://localhost:3000/ws
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=3000

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"

    # Security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100m,mode=1777,noexec,nosuid,nodev
      - /var/cache/nginx:size=100m,mode=755,noexec,nosuid,nodev
      - /var/run:size=10m,mode=755,noexec,nosuid,nodev

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        compress: "true"

networks:
  default:
    name: qwen-integration-test
