name: qwen2-image
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - torchvision=0.18.1
  - cudatoolkit=12.1
  - pip
  - pip:
      - -r requirements.txt
      - -c constraints.txt
