name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps to reproduce
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Relevant log output
