name: Feature Request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Proposal
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this feature useful?
    validations:
      required: true
